- name: Detect Defender install
  stat:
    path: /etc/opt/microsoft/mdatp/managed
  register: defender_config_dir

- name: Defender managed config
  copy:
    src: mdatp_managed.json
    dest: /etc/opt/microsoft/mdatp/managed/mdatp_managed.json
    owner: root
    group: root
    mode: 0o644
  when: defender_config_dir.stat.exists
